### ISSUE TITLE
make keywords easy [PLEASE]

### ISSUE THREAD

**Issue by OmiChrome** [jsmsj/megadrive-template-generator-v2#2]
i dont like to type 
`md template` , when there is no use of bot other than making template, 
why we need to explicitly describe `md template` , why not make it shorter 
as

`md` or `mt` , or `mdt` , any like this 
using small aliases would be great

**Comment by OmiChrome** [comment]
another reminder

**Comment by jsmsj** [comment]
Bro we aren't using the bot anymore. So no point updating it right now

**Comment by OmiChrome** [comment]
okay  👍
